django/mysite/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='home'),
    path('customers/',views.customers,name='customers'),
    path('books/',views.books, name='books'),
    path('login/',views.loginpage,name='login'),
    path('register/',views.registerpage,name='register'),
    path('logout/',views.logoutpage,name='logout'),
    path('addreview/<str:pk>/',views.createReview,name='addreview'),
    path('deletebook/<str:pk>/',views.deleteBook,name='deletebook'),
    path('booksearch/',views.bookSearch,name='booksearch'),

    path('bookdetail/<str:pk>/',views.bookDetail,name='bookdetail'),
    path('updatbook/<str:pk>/',views.updateBook,name='updatebook'),
    path('mybooks/',views.myBooks,name='mybooks'),
    path('myissuerequest/',views.myissuereqeuest,name='myissuerequest'),
    path('delwish/<str:pk>/',views.delWish,name='delwish'),
    path('moderator/',views.moderator,name='moderator'),
    path('addadmin/<str:pk>/',views.addAdmin,name='addadmin'),
    path('removeadmin/<str:pk>/',views.removeAdmin,name='removeadmin'),
    path('issuebook/<str:pk>/',views.issuebook,name='issuebook'),
    path('upvote/<str:pk>/',views.upvote,name='upvote'),
    path('removeupvote/<str:pk>/',views.rm_upvote,name='removeupvote'),
    path('downvote/<str:pk>/',views.downvote,name='downvote'),
    path('removedownvote/<str:pk>/',views.rm_downvote,name='removedownvote'),
    path('saveorder/<str:pk>/',views.saveOrder,name='saveorder'),
    path('savequery/',views.saveQuery,name='savequery'),
    path('viewquery/',views.viewQuery,name='viewquery'),
    path('browse/',views.browse,name='browse'),
    path('filterbook/',views.filterbook,name='filterbook'),
    path('booksuggestions/',views.booksuggestions,name='booksuggestions'),
]

django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),

]
urlpatterns += static('/images/bookimages/',document_root=settings.MEDIA_ROOT)

django/mysite/accounts/models.py
from django.contrib.auth.models import User

from django.db import models

# Create your models here.

class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    name=models.CharField(max_length=200,null=True)
    phone=models.CharField(max_length=200,null=True)
    email=models.EmailField(max_length=200,null=True)
    datecreated=models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name=models.CharField(null=True,max_length=200)

    def __str__(self):
        return self.name

class Language(models.Model):
    name=models.CharField(null=True,max_length=200)

    def __str__(self):
        return self.name

class Book(models.Model):

    name=models.CharField(max_length=200, null= True)
    category=models.ManyToManyField(Category,related_name='category')
    author=models.CharField(max_length=200,null=True)
    quantity=models.IntegerField(null=True,blank=True)
    language=models.ForeignKey(Language,on_delete=models.CASCADE,null=True,blank=True)
    dimennsions=models.CharField(max_length=100,null=True,blank=True)
    description=models.TextField(max_length=5000,null=True,blank=True)
    image=models.ImageField(default='defaultbook.png',null=True,blank=True)
    upvote=models.ManyToManyField(User,blank=True,related_name='upvote')
    downvote=models.ManyToManyField(User,blank=True,related_name='downvote')



    def __str__(self):
        return self.name

class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    book=models.ForeignKey(Book, max_length=200, on_delete=models.SET_NULL,null=True)
    Review=models.TextField(max_length=500,null=True)
    datecreated=models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.book.name

class Order(models.Model):
    STATUS=(('Rented','Rented'),('Pending','Pending'),('Returned','Returned'))
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    book=models.ForeignKey(Book, max_length=200, on_delete=models.SET_NULL,null=True)
    status=models.CharField(max_length=200, null=True,choices=STATUS)
    dateordered=models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.book.name

class customerQuery(models.Model):
    emailid=models.EmailField(max_length=200,null=True,blank=True)
    query=models.TextField(max_length=500,null=True,blank=True)

    def __str__(self):
        return self.emailid

django/mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from django.contrib.auth.models import User

from accounts.models import Book, Category, Order, Review, customerQuery

class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']
    

class AddReview(ModelForm):
    class Meta:
        model=Review
        fields=['user','book', 'Review']


class AddBook(ModelForm):
    class Meta:
        model=Book
        fields='__all__'
        exclude=['upvote','downvote']

class AddCategory(ModelForm):
    class Meta:
        model= Category
        fields='__all__'

class SearchOrder(ModelForm):
    class Meta:
        model=Order
        fields='__all__'

class Issue(ModelForm):
    class Meta:
        model=Order
        fields=['user','book','status']
class QueryForm(ModelForm):
    class Meta:
        model=customerQuery
        fields='__all__'

django/mysite/accounts/views.py
from unicodedata import category
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import AddBook, AddCategory, AddReview, CreateUserForm
from .decorators import unauthorizedUsers, allowedUsers
from django.contrib.auth.models import Group
from .filters import  Orderfilter
from django.urls import reverse
from django.http import JsonResponse

# Create your views here.

def test(request):
    return render(request,'accounts/test.html')

def main():
    group_customer=Group.objects.get(name='customer')
    customer_users=User.objects.filter(groups=group_customer)
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    context={'customer_users':customer_users,'admin_users':admin_users}
    return render('accounts/main.html',context)

def home(request):
    books=Book.objects.all()
    category=Category.objects.all()
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    context={'books':books,'admin_users':admin_users,'category':category}
    return render(request, 'accounts/home.html',context)

@login_required(login_url='login')
@allowedUsers(['admin'])

def customers(request):
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    orders=Order.objects.all().order_by('user','dateordered')
    myfilter=Orderfilter(request.GET,queryset=orders)
    orders=myfilter.qs
    context={'orders':orders,'myfilter':myfilter,'admin_users':admin_users}

    return render(request, 'accounts/customers.html',context)

@login_required(login_url='login')
@allowedUsers(['admin'])

def books(request):

    books=Book.objects.all()
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)

    form=AddBook()
    categoryform=AddCategory()


    if request.method == 'POST' :
            form= AddBook(request.POST)
            if form.is_valid():
                form.save()
                return redirect('books')

    if request.method == 'POST' :
            categoryform= AddCategory(request.POST)
            if categoryform.is_valid():
                categoryform.save()
                return redirect('books')

    return render(request, 'accounts/books.html',{'books':books, 'form':form, 'categoryform': categoryform,'admin_users':admin_users})

def registerpage(request):
    form= CreateUserForm()

    if request.method=='POST':
        form= CreateUserForm(request.POST)
        if form.is_valid():
            user=form.save()
            username=form.cleaned_data.get('username')

            group=Group.objects.get(name='customer')
            user.groups.add(group)
            if user is not None:
                login(request, user)
                return redirect('home')
    context={'form':form}
    return render(request, 'accounts/register.html',context)

@unauthorizedUsers

def loginpage(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, "Username или Password некорректные")

    context={}
    return render(request, 'accounts/login.html',context)

def logoutpage(request):
    logout(request)
    messages.info(request, "Вы успешно разлогинелись!")
    return redirect('home')

@login_required(login_url='login')

def createReview(request,pk):

    book=Book.objects.get(id=pk)
    user=request.user
    form=AddReview(initial={'book':book, 'user':user})
    if request.method == 'POST' :
            form= AddReview(request.POST)
            if form.is_valid():

                form.save()
                return redirect('books')
    context={'form' : form, 'book':book, 'user':user }
    return render (request,'accounts/review_form.html',context)

@login_required(login_url='login')
@allowedUsers(['admin'])

def deleteBook(request,pk):
    book_delete=Book.objects.get(id=pk)
    book_delete.delete()
    return redirect('books')

def filterbook(request):
    books=Book.objects.all()
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    filtered_books=Book.objects.none()
    category=Category.objects.all()
    languages=Language.objects.all()
    filters=[]
    categories= request.GET.getlist('category[]')
    filters+=categories
    for i in categories:
        category_book=Book.objects.filter(category__name=i)
        filtered_books=filtered_books.union(category_book)

    language= request.GET.getlist('language[]')
    filters+=language
    for i in language:
        language_book=Book.objects.filter(language__name=i)
        filtered_books=filtered_books.union(language_book)

    available= request.GET.get('available')
    filters.append(available)
    if (available=='available'):
        available_book=Book.objects.filter(quantity__gt=0)
        filtered_books=filtered_books.union(available_book)

    upvoted_books=[]
    upvoted= request.GET.get('upvotedbooks')
    filters.append(upvoted)
    if (upvoted=='upvoted'):
        for book in books:
            upvotes=book.upvote.count()
            downvotes=book.downvote.count()
            votes=upvotes-downvotes
            if (votes>0):
                upvoted_books.append(book)

        filtered_books=filtered_books.union(upvoted_books)
    books=filtered_books
    if(filters==[None, None]):
        books=Book.objects.all()
    context={'books':books,'admin_users':admin_users,'category':category,'languages':languages,'filters':filters}
    return render(request,'accounts/booksearch.html',context)

def browse(request):
    books=Book.objects.all()
    category=Category.objects.all()
    languages=Language.objects.all()
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    context={'books':books,'admin_users':admin_users,'category':category,'languages':languages}
    return render(request,'accounts/booksearch.html',context)

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def booksuggestions(request):
    if is_ajax(request):

        term=request.GET.get('term')
        books=Book.objects.filter(name__icontains=term)
        response_content=list(books.values())


        return JsonResponse(response_content,safe=False)

def bookSearch(request):
    books=Book.objects.none()
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    id=request.GET.get('name')

    books=Book.objects.filter(id=id)

    category=Category.objects.all()
    languages=Language.objects.all()
    context={'books':books,'admin_users':admin_users,'category':category,'languages':languages}
    return render(request,'accounts/booksearch.html',context)

@login_required(login_url='login')
@login_required(login_url='login')

def bookDetail(request,pk):
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    book=Book.objects.get(id=pk)
    reviews=book.review_set.all()
    length=len(reviews)
    user=request.user
    uv=book.upvote.all()
    dv=book.downvote.all()
    similar_categories=list(book.category.all())
    similar_books=Book.objects.none()
    for category in similar_categories:


        similar_cat_books=Book.objects.filter(category__name=category.name).exclude(name=book.name)

        similar_books=similar_books.union(similar_cat_books)

    upvotes=book.upvote.count()
    downvotes=book.downvote.count()
    votes=upvotes-downvotes
    pending=user.order_set.filter(book=book,status='Pending')
    issued=user.order_set.filter(book=book,status='Rented')
    context={'book':book,'similar_books':similar_books,'reviews':reviews,'pending':pending,'issued':issued,'votes':votes,'uv':uv,'dv':dv,'admin_users':admin_users,'length':length}
    return render(request,'accounts/bookdetail.html',context)


@login_required(login_url='login')

def myBooks(request):
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    user=request.user
    orders=user.order_set.filter(status='Rented')
    context={'orders':orders,'admin_users':admin_users}
    return render(request,'accounts/mybooks.html',context)

@login_required(login_url='login')

def myissuereqeuest(request):
    user=request.user
    group_admin=Group.objects.get(name='admin')
    admin_users=User.objects.filter(groups=group_admin)
    orders=user.order_set.filter(status='Pending')

    context={'orders':orders,'admin_users':admin_users}
    return render(request,'accounts/myissuerequest.html',context)

@login_required(login_url='login')
@allowedUsers(['admin'])

def saveOrder(request,pk):
    order=Order.objects.get(id=pk)
    order.status=request.POST.get('status')
    q=order.book.quantity
    if request.method=="POST":
        if request.POST.get('status')=='Rented':
            q=q-1
            book=Book.objects.get(name=order.book.name)
            book.quantity=q
            book.save()
        if request.POST.get('status')=='Returned':
            q=q+1
            book=Book.objects.get(name=order.book.name)
            book.quantity=q
            book.save()
        order.save()
        return redirect('home')

@login_required(login_url='login')
@allowedUsers(['admin'])

def updateBook(request,pk):
    book=Book.objects.get(id=pk)
    update=AddBook(instance=book)
    if request.method=="POST":
        update=AddBook(request.POST,instance=book)
        if update.is_valid():
            update.save()
            return redirect('books')

django/mysite/accounts/templates/accounts/books.html
{% extends 'accounts/main.html' %} {% block content %}

<style>
  .themebtn{
    border:1px solid #c3c1bf;
  }
  .themebtn:hover{
    border:1px solid #c3c1bf;
    background-color: #c3c1bf;
    color: white;
  }
</style>

<br />

<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <h5>Книги</h5>
    </div>
    <div class="card card-body">

      <!-- Button trigger modal -->
      <button
        type="button"
        class="btn btn-primary mb-2"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal1"
      >
        Добавить книги
      </button>


      <!-- Modal -->
      <div
        class="modal fade"
        id="exampleModal1"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >

        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel1">Добавить книги</h5>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>

            <div class="modal-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.name.label}}
                    {{form.name}}
                    <br>
                    {{form.category.label}}
                    {{form.category}}
                    <br>
                    {{form.author.label}}
                    {{form.author}}
                    <br>
                    {{form.description.label}}
                    {{form.description}}
                    <br>
                    {{form.language.label}}
                    {{form.language}}
                    <br>
                    {{form.quantity.label}}
                    {{form.quantity}}
                    <br>
                    {{form.image.label}}
                    {{form.image}}

                </div>
                <div class="modal-footer">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                  >
                    Close
                  </button>
                   <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>

            </div>
          </div>
        </div>
      </div>



          <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal2">
 Добавить категорию
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-2" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Добавить категорию</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="" method="POST">
            {% csrf_token %}
            {{categoryform.name.label}}
            {{categoryform.name}}

        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
           <button type="submit" class="btn">Сохранить</button>
        </form>

    </div>

    </div>
  </div>
</div>



      <table class="table">
        <tr>
          <th>Книги</th>

          <th></th>
          <th></th>
          <th></th>
        </tr>

        {% for i in books %}
        <tr>
          <td>{{i.name}}</td>

          <td><a href="{% url 'updatebook' i.id %}" role="button" class="btn themebtn me-2">Изменить книгу</a></td>




            <td>
              <a
                class="btn btn-outline-danger me-2"
                href="{% url 'deletebook' i.id %}"
                role="button"
                >Удалить</a
              >
            </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock %}

django/mysite/accounts/templates/accounts/booksearch.html
{% extends 'accounts/main.html' %} {% load static %} {% block content %}

<div class="row mt-3">
  <div class="col-2 border">
    <div id="bookfilter">
      <form action="{% url 'filterbook' %}" method="GET">
        {% csrf_token %}

        <div id="categorycontainer">
          <ul style="list-style: none">
            <h5>Категории</h5>

            {% for category in category %}
            <li>
              <label for="{{category.name}}">{{category.name}}</label>
              <input
                type="checkbox"
                id="{{category.name}}"
                name="category[]"
                value="{{category.name}}"
              />
            </li>

            {% endfor %}
          </ul>
        </div>
        <div id="languagecontainer">
          <ul class="filter" style="list-style: none">
            <h5>Языки</h5>
            {% for language in languages %}
            <li>
              <label for="{{language.name}}">{{language.name}}</label>
              <input
                type="checkbox"
                id="{{language.name}}"
                name="language[]"
                value="{{language.name}}"
              />
            </li>

            {% endfor %}
          </ul>
        </div>
        <div id="availabilty">
          <ul class="filter" style="list-style: none">
            <h5>В наличии</h5>
            <li>
              <label for="available">Только в наличии</label>
              <input
                type="checkbox"
                name="available"
                id="available"
                value="available"
              />
            </li>
          </ul>
        </div>
        <div id="likedbooks">
          <ul class="filter" style="list-style: none">
            <h5>Книги с рейтингом</h5>
            <li>
              <label for="upvotedbooks">Книги с положительным рейтингом</label>
              <input
                type="checkbox"
                name="upvotedbooks"
                id="upvotedbooks"
                value="upvoted"
              />
            </li>
          </ul>
        </div>
        <input
          type="submit"
          role="btn"
          class="btn themebtn mb-2"
          style="margin-left: 30px"
          value="Применить фильтр"
          id="filterbtn"
        />
      </form>
    </div>
  </div>

  <br /><br /><br />
  {% comment %}
  <div style="justify-content: center; align-items: center; display: flex">
    {% if bn %} {% for book in bn %}
    <b> You searched for "{{book.name}} "</b>
    {% endfor %} {% elif bc %}

    <b>You searched for "{{category}} "</b>
    {% else %}
    <b style="font-size: 25px">No results matched</b>
    {%endif%}
  </div>
  {% endcomment %}
  <br />
  <div class="col-10 border">
    <div class="filtertags mt-4 mb-4">
      {% for filter in filters %} {% if filter is not None %}
      <span class="badge rounded-pill bg-secondary">{{filter}}</span>

      {% endif %} {% endfor %} {% if filters is not None %}
      <a
        class="btn btn-sm btn-outline-secondary"
        href="{% url 'browse' %}"
        role="button"
        >Очистить все фильтры</a
      >
      {% endif %}
    </div>

    <div class="card-group">
      <div class="row ">
        {% for i in books %}

        <div class="col mx-2 mb-3">
          <div class="card card-container" style="width: 280px">
            <img
              src="{{i.image.url}} "
              style="height: 300px"
              class="card-img-top"
              alt="..."
            />
            <div class="card-body">
              <a href="{% url 'bookdetail' i.id %} " class="booklink text-center"
                ><h5 class="card-title">{{i.name}}</h5></a
              >
              <p class="card-text text-center">{{i.author}}</p>
              {% if i.quantity %}
              <p class="card-text text-center" style="color: green">В НАЛИЧИИ</p>
              {% else %}
              <p class="card-text text-center" style="color: red">НЕДОСТУПНА</p>
              {% endif %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<style>
  .booklink {
    text-decoration: none;
  }
  .booklink:hover{
    color: rgb(77, 37, 37);
  }

  .card:hover {
    box-shadow: 2px 2px 2px 1px grey;
  }
  .filter {
    list-style: none;
  }
  .card-container:hover{
    background-color: #c3c1bf96
  }

  .themebtn {
    border: 2px solid #c3c1bf;
  }
  .themebtn:hover {
    border: 2px solid #c3c1bf;
    background-color: #c3c1bf;
    color: white;
  }
</style>
{% endblock %}

django/mysite/accounts/templates/accounts/customers.html
{% extends 'accounts/main.html' %} {% block content %}

<style>

  #id_user{
    width: 25%;
  }
#searchorder{
  justify-content: center;
  align-items: end;
  display: flex
}
label{
  padding: 10px;
}
#searchorder select,#searchorder span{
  height: 40px;
}
#select2-id_user-container{
  height: 40px;
}

</style>
<br><br>
<br><br>
<form id="searchorder" action="" method="GET">

  {% csrf_token %}
  {{myfilter.form}}
<button class="btn btn-secondary mx-2 search input" type="submit">Поиск</button>

</form>
<br>
<div class="btns" style="display:flex;padding: 10px; justify-content: center; align-items: center; ">
  <a href="{% url 'viewquery' %}" type="button" class="btn btn-outline-secondary me-5">Показать запросы</a>
  <a href="{% url 'moderator' %}" type="button" class="btn btn-outline-secondary me-2">Отправить Модератору</a>
</div>
<div style="height: 52vh;justify-content: center; align-items:top; display: flex; width: 70%;">
  <div class="row" >
    <div class="col-md">
      <div class="card card-body" style="width: 230%;">
        <table class="table table-success tabble-stripped table-sm" style="justify-content: center; align-items: center; ">
          <thead class="table-dark">

            <tr>
              <th>Заказчик</th>
              <th>Книга</th>


              <th>Статус</th>
              <th></th>

            </tr>
          </thead>
          <tbody>

            {% for i in orders %}
            <tr>
              <form action="{% url 'saveorder' i.id  %}" method="POST">
                {% csrf_token %}
                <td>{{i.user}}</td>
                <td>{{i.book.name}}</td>

                <td><select name="status" class="form-select" aria-label="Default select example">
                  <option selected>{{i.status}}</option>
                  <option value="Rented">Получена</option>
                  <option value="Pending">Ожидает</option>
                  <option value="Returned">Возвращена</option>
                </select></td>
                <td>
                  <input type="submit" value="Update" class="btn btn-primary  sm" style="width: 100%;" >
                </td>
              </form>
            </tr>
          </tbody>

        {% endfor %}
      </table>
    </div>
  </div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
  $(document).ready(function() {
    $('#id_user').select2();
});
</script>

{% endblock %}

django/mysite/accounts/templates/accounts/login.html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mulish:wght@200&display=swap" rel="stylesheet">

<style>
  .logintext{
    color: blanchedalmond;
    font-family: 'Mulish', sans-serif;
  }
  body{

  display: flex;
  background: url('/static/images/logpage.jpeg');
  backdrop-filter:blur(1.0px);
  justify-content:center;
  align-items: center;
}

#login {
  background: #080e12b0;
  /* border: 2px solid rgb(22, 101, 175); */
  margin: 50px;
  padding: 50px;
  /* position: absolute;
  justify-content: center;
  align-items:center ; */
}
.btn{

  padding: 10px;
  cursor: pointer;
  color: white;
  background: #080e12b0;
  border: 2px solid white;
  width: 100%;
}
.btn:hover{
  background-color: white;
  color: black;
  width: 100%;

  padding: 10px;

}
.input{
  width: 100%;
  padding: 10px;
  color: white;
  background: #36495594;
  border: 2px solid white;
}
.url{
  color: aquamarine;
}
</style>
  <body>
    <div
    class="login" >

      <form id="login" method="POST" action="/login/">
        <h2 class="logintext" style="text-align: center;">ВХОД</h2>
        <br >
        {% csrf_token %}

        <input name="username" type="text" placeholder="username" class="input" />
        <br >
        <br>

        <input type="password" placeholder="password" name="password" class="input"/>
        <br >
        <br >
        <button type="submit" class="btn ">Вход</button>
        <br >
        <br >
        {% for message in messages %}
        <p class="logintext" id="messages">{{message}}</p>
        {% endfor %}
        <p class="logintext">У вас нет аккаунта? <a class="url"href="{% url 'register' %}">Зарегистрируйтесь</a></p>
      </form>

  </div>
</body>

django/mysite/accounts/templates/accounts/queries.html
{% extends 'accounts/main.html' %} {% block content %}

<br />

<br />

<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <table class="table table-sm">
        <tr>
          <th>Email</th>
          <th>Запрос</th>

        </tr>
        {% for i in queries %}
        <tr>
          <td>{{i.emailid}}</td>
          <td>{{i.query}}</td>

        </tr>

        {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock %}

django/mysite/accounts/templates/accounts/updatebook.html
<style>
    @import url(https://fonts.googleapis.com/css?family=Alegreya+Sans:300);
    body{
        background: url('/static/images/bgedit.jpg') no-repeat center center/cover;
        backdrop-filter:blur(6px);
        justify-content:center;
        align-items: center;
        display: flex;
        font-family: 'Alegreya Sans', sans-serif;
    }
    .container{
        width: 300px;
        background-color: rgba(0, 0, 0, 0.45);
        border: 5px solid wheat;
        width: 25%;
        color: rgb(238, 225, 44);
    }
    form{
        font-size: 1.2em;
        font-weight:bolder;
        padding: 35px;
        display: flex;
        flex-direction: column;
    }
    input{
        background-color: rgba(59, 54, 54, 0.219);
        color: white;
        border: 1px solid white;
        padding: 5px;
        border-radius: 10px;
    }
    #id_description{
        background-color: rgba(59, 54, 54, 0.219);
        color: white;
        border: 1px solid white;
        padding: 5px;
        border-radius: 10px;

    }
    select{
        background-color: rgba(59, 54, 54, 0.219);
        color: white;
        border: 1px solid white;
        padding: 5px;
        border-radius: 10px;
    }
    select option{
        color: black;
    }

    label{
        padding-top: 12px;
    }
    #id_image{
        border: none;
        background:none;
    }
    #edit{
        height: 40px;
        border: 1px solid wheat;
    }
    #edit:hover{
        height: 40px;
        background-color: wheat;
        color: black;
        
    }
    a{
        color:whitesmoke;
    }
    #image-clear_id{
        display: none;
    }
  
</style>
<div class="container">

    <form action="" method="POST">
        
        {% csrf_token %}
        {{update}}
        <input id="edit" type="submit" role="button" class="btn">
    </form>
</div>